version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: QRTZ_DB
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      # initialize all quartz tables if not exist
      - ./QRTZ_DB.sql:/docker-entrypoint-initdb.d/QRTZ_DB.sql
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-network

networks:
  mysql-network:
    name: mysql-network
